"""Almide module: mathlib — auto-generated by almide-bridge"""
import ctypes, struct, os

_dir = os.path.dirname(os.path.abspath(__file__))
_lib = ctypes.CDLL(os.path.join(_dir, 'libalmide_mathlib.dylib'))

class Point:
    """A 2D point with x and y coordinates."""
    def __init__(self, x: float, y: float):
        self.x = x
        self.y = y

    def __repr__(self): return f'Point(x={self.x}, y={self.y})'
    def __eq__(self, other): return isinstance(other, Point) and self.x == other.x and self.y == other.y
    def __hash__(self): return hash((self.x, self.y))

class Shape:
    """A geometric shape."""
    def __init__(self, tag, *values):
        self.tag = tag
        self.values = values
    @staticmethod
    def circle(value): return Shape('Circle', value)
    @staticmethod
    def rect(v0, v1): return Shape('Rect', v0, v1)
    def __repr__(self):
        vals = ', '.join(str(v) for v in self.values)
        return f'Shape.{self.tag}({vals})' if vals else f'Shape.{self.tag}'
    def __eq__(self, other): return isinstance(other, Shape) and self.tag == other.tag and self.values == other.values
    def __hash__(self): return hash((self.tag, self.values))

def distance(a: Point, b: Point) -> float:
    """Euclidean distance between two points."""
    buf = b''
    buf += struct.pack('>d', a.x)
    buf += struct.pack('>d', a.y)
    buf += struct.pack('>d', b.x)
    buf += struct.pack('>d', b.y)
    _out = ctypes.create_string_buffer(4096)
    _rlen = _lib.bridge_distance(buf, len(buf), _out, 4096)
    _rbuf = _out.raw[:_rlen]
    _pos = 0
    _v, = struct.unpack_from('>d', _rbuf, _pos); _pos += 8
    return _v

def area(shape: Shape) -> float:
    """Area of a geometric shape."""
    buf = b''
    if shape.tag == 'Circle':
        buf += struct.pack('>I', 0)
        buf += struct.pack('>d', shape.values[0])
    elif shape.tag == 'Rect':
        buf += struct.pack('>I', 1)
        buf += struct.pack('>d', shape.values[0])
        buf += struct.pack('>d', shape.values[1])
    _out = ctypes.create_string_buffer(4096)
    _rlen = _lib.bridge_area(buf, len(buf), _out, 4096)
    _rbuf = _out.raw[:_rlen]
    _pos = 0
    _v, = struct.unpack_from('>d', _rbuf, _pos); _pos += 8
    return _v

def midpoint(a: Point, b: Point) -> Point:
    """Midpoint between two points."""
    buf = b''
    buf += struct.pack('>d', a.x)
    buf += struct.pack('>d', a.y)
    buf += struct.pack('>d', b.x)
    buf += struct.pack('>d', b.y)
    _out = ctypes.create_string_buffer(4096)
    _rlen = _lib.bridge_midpoint(buf, len(buf), _out, 4096)
    _rbuf = _out.raw[:_rlen]
    _pos = 0
    _f_x, = struct.unpack_from('>d', _rbuf, _pos); _pos += 8
    _f_y, = struct.unpack_from('>d', _rbuf, _pos); _pos += 8
    _v = Point(x=_f_x, y=_f_y)
    return _v

def describe(shape: Shape) -> str:
    """Human-readable description of a shape."""
    buf = b''
    if shape.tag == 'Circle':
        buf += struct.pack('>I', 0)
        buf += struct.pack('>d', shape.values[0])
    elif shape.tag == 'Rect':
        buf += struct.pack('>I', 1)
        buf += struct.pack('>d', shape.values[0])
        buf += struct.pack('>d', shape.values[1])
    _out = ctypes.create_string_buffer(4096)
    _rlen = _lib.bridge_describe(buf, len(buf), _out, 4096)
    _rbuf = _out.raw[:_rlen]
    _pos = 0
    _slen, = struct.unpack_from('>I', _rbuf, _pos); _pos += 4
    _v = _rbuf[_pos:_pos+_slen].decode('utf-8'); _pos += _slen
    return _v
