"""
Generate C FFI wrapper: read interface.json + mathlib.rs -> extern "C" lib + C header.

Patterns:
  - Record types  -> #[repr(C)] struct, params flattened to scalars, returns via out-pointer
  - Variant types -> flattened to one extern "C" fn per case (C has no sum types)
  - String return -> *const c_char (caller frees with almide_free_string)
  - Scalars       -> passed/returned directly
"""
import json
import argparse
import os
import sys

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
ap = argparse.ArgumentParser(description="Generate C FFI wrapper from Almide interface")
ap.add_argument("--interface", default="interface.json", help="Path to interface.json")
ap.add_argument("--rust-src", default="mathlib.rs", help="Path to Almide-generated Rust source")
ap.add_argument("--out-dir", default=".", help="Output directory (writes src/lib.rs, Cargo.toml, header)")
args = ap.parse_args()

with open(args.interface) as f:
    iface = json.load(f)

with open(args.rust_src) as f:
    rust_source = f.read()

module = iface["module"]
lib_name = f"almide_{module}"
out_dir = args.out_dir

# ---------------------------------------------------------------------------
# Type helpers
# ---------------------------------------------------------------------------
# Resolve type defs from interface for lookup
type_defs = {t["name"]: t for t in iface["types"]}


def rust_type(tref):
    k = tref["kind"]
    if k == "float":
        return "f64"
    if k == "int":
        return "i64"
    if k == "string":
        return "String"
    if k == "bool":
        return "bool"
    if k == "named":
        return tref["name"]
    if k == "option":
        return f"Option<{rust_type(tref['inner'])}>"
    if k == "list":
        return f"Vec<{rust_type(tref['inner'])}>"
    return "/* unknown */"


def c_scalar_type(tref):
    """Map Almide TypeRef to C type for scalars."""
    k = tref["kind"]
    if k == "float":
        return "double"
    if k == "int":
        return "int64_t"
    if k == "bool":
        return "int"
    if k == "string":
        return "const char*"
    return None  # not a scalar


def is_scalar(tref):
    return tref["kind"] in ("float", "int", "bool", "string")


def is_record(tref):
    return tref["kind"] == "named" and tref["name"] in type_defs and type_defs[tref["name"]]["kind"]["kind"] == "record"


def is_variant(tref):
    return tref["kind"] == "named" and tref["name"] in type_defs and type_defs[tref["name"]]["kind"]["kind"] == "variant"


def record_fields(name):
    return type_defs[name]["kind"]["fields"]


def variant_cases(name):
    return type_defs[name]["kind"]["cases"]


def c_type_for_return(tref):
    """C return type. Records return void (out-pointer), strings return const char*."""
    if tref["kind"] == "string":
        return "const char*"
    if is_record(tref):
        return "void"
    return c_scalar_type(tref)


def c_struct_name(name):
    return name


# ---------------------------------------------------------------------------
# Flatten record params into scalar args
# ---------------------------------------------------------------------------
def flatten_record_params(prefix, rec_name):
    """Return list of (c_arg_name, c_type, rust_field_name) for a record flattened into scalars."""
    result = []
    for f in record_fields(rec_name):
        ft = f["type"]
        arg_name = f"{prefix}{f['name']}"
        if is_scalar(ft):
            result.append((arg_name, c_scalar_type(ft), f["name"]))
        elif is_record(ft):
            # Nested record: recurse
            result.extend(flatten_record_params(f"{arg_name}_", ft["name"]))
        else:
            # Fallback: opaque
            result.append((arg_name, "void*", f["name"]))
    return result


# ---------------------------------------------------------------------------
# Generate src/lib.rs
# ---------------------------------------------------------------------------
rs = []
rs.append("// AUTO-GENERATED by generate_c_ffi.py -- do not edit")
rs.append("use std::ffi::CString;")
rs.append("use std::os::raw::c_char;")
rs.append("")

# Include Almide-generated Rust (stripped of boilerplate)
for line in rust_source.split("\n"):
    if line.startswith("#![allow"):
        continue
    if line.startswith("use std::collections"):
        continue
    if "fn main(" in line:
        continue
    rs.append(line)
rs.append("")

# #[repr(C)] structs for record types
for t in iface["types"]:
    if t["kind"]["kind"] == "record":
        name = t["name"]
        rs.append(f"#[repr(C)]")
        rs.append(f"pub struct C{name} {{")
        for f in t["kind"]["fields"]:
            ct = c_scalar_type(f["type"])
            if ct is None:
                ct = "f64"  # fallback
            # Map C types back to Rust repr(C) types
            rust_repr = {"double": "f64", "int64_t": "i64", "int": "i32"}.get(ct, "f64")
            rs.append(f"    pub {f['name']}: {rust_repr},")
        rs.append("}")
        rs.append("")

# Free-string helper
rs.append("/// Free a string returned by an almide C FFI function.")
rs.append("#[no_mangle]")
rs.append("pub extern \"C\" fn almide_free_string(s: *mut c_char) {")
rs.append("    if s.is_null() { return; }")
rs.append("    unsafe { drop(CString::from_raw(s)); }")
rs.append("}")
rs.append("")


def build_reconstruct_record(prefix, rec_name):
    """Build Rust expression that reconstructs an Almide record from flat C args."""
    parts = []
    for f in record_fields(rec_name):
        ft = f["type"]
        arg = f"{prefix}{f['name']}"
        if is_scalar(ft):
            parts.append(f"{f['name']}: {arg}")
        elif is_record(ft):
            inner = build_reconstruct_record(f"{arg}_", ft["name"])
            parts.append(f"{f['name']}: {inner}")
        else:
            parts.append(f"{f['name']}: {arg}")
    return f"{rec_name} {{ {', '.join(parts)} }}"


# Generate extern "C" wrapper functions
for fn_def in iface["functions"]:
    fname = fn_def["name"]
    ret = fn_def["return"]

    # Check if any param is a variant (need flattening per case)
    variant_params = [(i, p) for i, p in enumerate(fn_def["params"]) if is_variant(p["type"])]

    if variant_params:
        # Generate one extern "C" fn per variant case combination
        # For simplicity: support one variant param (covers the common case)
        assert len(variant_params) == 1, "Multiple variant params not yet supported"
        vi, vparam = variant_params[0]
        vtype_name = vparam["type"]["name"]
        cases = variant_cases(vtype_name)

        # Non-variant params
        other_params = [(i, p) for i, p in enumerate(fn_def["params"]) if i != vi]

        for case in cases:
            case_name = case["name"]
            case_lower = case_name.lower()
            extern_name = f"almide_{fname}_{case_lower}"

            # Build parameter list
            c_params = []
            rust_param_strs = []

            # Non-variant params (before and after the variant)
            for oi, op in other_params:
                pt = op["type"]
                if is_record(pt):
                    flat = flatten_record_params(f"{op['name']}", pt["name"])
                    for arg_name, ct, _ in flat:
                        rtype = {"double": "f64", "int64_t": "i64", "int": "i32"}.get(ct, "f64")
                        rust_param_strs.append(f"{arg_name}: {rtype}")
                elif is_scalar(pt):
                    rtype = {"double": "f64", "int64_t": "i64", "int": "i32", "const char*": "*const c_char"}.get(c_scalar_type(pt), "f64")
                    rust_param_strs.append(f"{op['name']}: {rtype}")

            # Variant case payload fields
            payload_args = []
            if case.get("payload"):
                pk = case["payload"]["kind"]
                if pk == "tuple":
                    for fi, ft in enumerate(case["payload"]["fields"]):
                        arg_name = f"v{fi}" if len(case["payload"]["fields"]) > 1 else "v0"
                        rtype = {"double": "f64", "int64_t": "i64", "int": "i32"}.get(c_scalar_type(ft), "f64")
                        rust_param_strs.append(f"{arg_name}: {rtype}")
                        payload_args.append(arg_name)

            # Out-pointer for record returns
            if is_record(ret):
                rust_param_strs.append(f"out: *mut C{ret['name']}")

            params_str = ", ".join(rust_param_strs)

            # Build call to the original Almide fn
            call_args = []
            for oi, op in other_params:
                pt = op["type"]
                if is_record(pt):
                    call_args.append(build_reconstruct_record(op["name"], pt["name"]))
                else:
                    call_args.append(op["name"])

            # Construct variant value
            if payload_args:
                variant_expr = f"{vtype_name}::{case_name}({', '.join(payload_args)})"
            else:
                variant_expr = f"{vtype_name}::{case_name}"

            # Insert variant arg at original position
            call_args.insert(vi, variant_expr)
            call_str = f"{fname}({', '.join(call_args)})"

            # Return type handling
            if ret["kind"] == "string":
                rs.append(f"#[no_mangle]")
                rs.append(f"pub extern \"C\" fn {extern_name}({params_str}) -> *const c_char {{")
                rs.append(f"    let s = {call_str};")
                rs.append(f"    CString::new(s).unwrap().into_raw() as *const c_char")
                rs.append(f"}}")
            elif is_record(ret):
                rs.append(f"#[no_mangle]")
                rs.append(f"pub extern \"C\" fn {extern_name}({params_str}) {{")
                rs.append(f"    let r = {call_str};")
                rs.append(f"    unsafe {{")
                for f in record_fields(ret["name"]):
                    rs.append(f"        (*out).{f['name']} = r.{f['name']};")
                rs.append(f"    }}")
                rs.append(f"}}")
            else:
                c_ret = c_scalar_type(ret)
                rust_ret = {"double": "f64", "int64_t": "i64", "int": "i32"}.get(c_ret, "f64")
                rs.append(f"#[no_mangle]")
                rs.append(f"pub extern \"C\" fn {extern_name}({params_str}) -> {rust_ret} {{")
                rs.append(f"    {call_str}")
                rs.append(f"}}")
            rs.append("")

    else:
        # No variant params: generate a single extern "C" fn
        extern_name = f"almide_{fname}"

        rust_param_strs = []
        for p in fn_def["params"]:
            pt = p["type"]
            if is_record(pt):
                flat = flatten_record_params(p["name"], pt["name"])
                for arg_name, ct, _ in flat:
                    rtype = {"double": "f64", "int64_t": "i64", "int": "i32"}.get(ct, "f64")
                    rust_param_strs.append(f"{arg_name}: {rtype}")
            elif is_scalar(pt):
                rtype = {"double": "f64", "int64_t": "i64", "int": "i32", "const char*": "*const c_char"}.get(c_scalar_type(pt), "f64")
                rust_param_strs.append(f"{p['name']}: {rtype}")

        # Out-pointer for record returns
        if is_record(ret):
            rust_param_strs.append(f"out: *mut C{ret['name']}")

        params_str = ", ".join(rust_param_strs)

        # Build call
        call_args = []
        for p in fn_def["params"]:
            pt = p["type"]
            if is_record(pt):
                call_args.append(build_reconstruct_record(p["name"], pt["name"]))
            else:
                call_args.append(p["name"])
        call_str = f"{fname}({', '.join(call_args)})"

        if ret["kind"] == "string":
            rs.append(f"#[no_mangle]")
            rs.append(f"pub extern \"C\" fn {extern_name}({params_str}) -> *const c_char {{")
            rs.append(f"    let s = {call_str};")
            rs.append(f"    CString::new(s).unwrap().into_raw() as *const c_char")
            rs.append(f"}}")
        elif is_record(ret):
            rs.append(f"#[no_mangle]")
            rs.append(f"pub extern \"C\" fn {extern_name}({params_str}) {{")
            rs.append(f"    let r = {call_str};")
            rs.append(f"    unsafe {{")
            for f in record_fields(ret["name"]):
                rs.append(f"        (*out).{f['name']} = r.{f['name']};")
            rs.append(f"    }}")
            rs.append(f"}}")
        else:
            c_ret = c_scalar_type(ret)
            rust_ret = {"double": "f64", "int64_t": "i64", "int": "i32"}.get(c_ret, "f64")
            rs.append(f"#[no_mangle]")
            rs.append(f"pub extern \"C\" fn {extern_name}({params_str}) -> {rust_ret} {{")
            rs.append(f"    {call_str}")
            rs.append(f"}}")
        rs.append("")

# ---------------------------------------------------------------------------
# Generate Cargo.toml
# ---------------------------------------------------------------------------
cargo = f"""[package]
name = "almide-{module}-c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "{lib_name}"
"""

# ---------------------------------------------------------------------------
# Generate C header
# ---------------------------------------------------------------------------
h = []
h.append(f"/* AUTO-GENERATED by generate_c_ffi.py -- do not edit */")
h.append(f"#ifndef {lib_name.upper()}_H")
h.append(f"#define {lib_name.upper()}_H")
h.append("")
h.append("#include <stdint.h>")
h.append("")

# Struct declarations for record types
for t in iface["types"]:
    if t["kind"]["kind"] == "record":
        name = t["name"]
        h.append(f"typedef struct {{")
        for f in t["kind"]["fields"]:
            ct = c_scalar_type(f["type"]) or "double"
            h.append(f"    {ct} {f['name']};")
        h.append(f"}} {name};")
        h.append("")

# Free-string
h.append("void almide_free_string(char* s);")
h.append("")

# Function declarations
for fn_def in iface["functions"]:
    fname = fn_def["name"]
    ret = fn_def["return"]

    variant_params = [(i, p) for i, p in enumerate(fn_def["params"]) if is_variant(p["type"])]

    if variant_params:
        vi, vparam = variant_params[0]
        vtype_name = vparam["type"]["name"]
        cases = variant_cases(vtype_name)
        other_params = [(i, p) for i, p in enumerate(fn_def["params"]) if i != vi]

        for case in cases:
            case_name = case["name"]
            case_lower = case_name.lower()
            extern_name = f"almide_{fname}_{case_lower}"

            c_params = []
            for oi, op in other_params:
                pt = op["type"]
                if is_record(pt):
                    flat = flatten_record_params(op["name"], pt["name"])
                    for arg_name, ct, _ in flat:
                        c_params.append(f"{ct} {arg_name}")
                elif is_scalar(pt):
                    c_params.append(f"{c_scalar_type(pt)} {op['name']}")

            if case.get("payload"):
                if case["payload"]["kind"] == "tuple":
                    for fi, ft in enumerate(case["payload"]["fields"]):
                        ct = c_scalar_type(ft) or "double"
                        arg_name = f"v{fi}" if len(case["payload"]["fields"]) > 1 else "v0"
                        c_params.append(f"{ct} {arg_name}")

            c_ret = c_type_for_return(ret) or "double"
            if is_record(ret):
                c_params.append(f"{ret['name']}* out")
            params_str = ", ".join(c_params) if c_params else "void"
            h.append(f"{c_ret} {extern_name}({params_str});")
    else:
        extern_name = f"almide_{fname}"
        c_params = []
        for p in fn_def["params"]:
            pt = p["type"]
            if is_record(pt):
                flat = flatten_record_params(p["name"], pt["name"])
                for arg_name, ct, _ in flat:
                    c_params.append(f"{ct} {arg_name}")
            elif is_scalar(pt):
                c_params.append(f"{c_scalar_type(pt)} {p['name']}")

        c_ret = c_type_for_return(ret) or "double"
        if is_record(ret):
            c_params.append(f"{ret['name']}* out")
        params_str = ", ".join(c_params) if c_params else "void"
        h.append(f"{c_ret} {extern_name}({params_str});")

h.append("")
h.append(f"#endif /* {lib_name.upper()}_H */")
h.append("")

# ---------------------------------------------------------------------------
# Write output files
# ---------------------------------------------------------------------------
src_dir = os.path.join(out_dir, "src")
os.makedirs(src_dir, exist_ok=True)

with open(os.path.join(src_dir, "lib.rs"), "w") as f:
    f.write("\n".join(rs) + "\n")

with open(os.path.join(out_dir, "Cargo.toml"), "w") as f:
    f.write(cargo)

with open(os.path.join(out_dir, f"{lib_name}.h"), "w") as f:
    f.write("\n".join(h) + "\n")

print(f"Generated: src/lib.rs, Cargo.toml, {lib_name}.h")
