"""
Simulate almide-export: read interface.json + mathlib.rs → generate PyO3 wrapper.
This is what the export tool would do automatically.
"""
import json

with open("interface.json") as f:
    iface = json.load(f)

with open("mathlib.rs") as f:
    rust_source = f.read()

# Type mapping: Almide TypeRef → Rust type string (for PyO3)
def rust_type(tref):
    k = tref["kind"]
    if k == "float": return "f64"
    if k == "int": return "i64"
    if k == "string": return "String"
    if k == "bool": return "bool"
    if k == "named": return tref["name"]
    if k == "option": return f"Option<{rust_type(tref['inner'])}>"
    if k == "list": return f"Vec<{rust_type(tref['inner'])}>"
    return "/* unknown */"

# Type mapping: Almide TypeRef → Python type hint string
def py_type(tref):
    k = tref["kind"]
    if k == "float": return "float"
    if k == "int": return "int"
    if k == "string": return "str"
    if k == "bool": return "bool"
    if k == "named": return tref["name"]
    if k == "option": return f"{py_type(tref['inner'])} | None"
    if k == "list": return f"list[{py_type(tref['inner'])}]"
    return "Any"

lines = []
lines.append("// AUTO-GENERATED by almide-export — do not edit")
lines.append("use pyo3::prelude::*;")
lines.append("")

# Include the Almide-generated Rust (stripped of #![allow] and main)
for line in rust_source.split("\n"):
    if line.startswith("#![allow"): continue
    if line.startswith("use std::collections"): continue
    if "fn main(" in line: continue
    lines.append(line)
lines.append("")

# Generate PyO3 wrappers for record types
for t in iface["types"]:
    name = t["name"]
    if t["kind"]["kind"] == "record":
        fields = t["kind"]["fields"]
        lines.append(f'#[pyclass(name = "{name}")]')
        lines.append(f'#[derive(Clone)]')
        lines.append(f'struct Py{name} {{')
        for f in fields:
            lines.append(f'    #[pyo3(get, set)]')
            lines.append(f'    {f["name"]}: {rust_type(f["type"])},')
        lines.append(f'}}')
        lines.append(f'#[pymethods]')
        lines.append(f'impl Py{name} {{')
        params = ", ".join(f'{f["name"]}: {rust_type(f["type"])}' for f in fields)
        lines.append(f'    #[new]')
        lines.append(f'    fn new({params}) -> Self {{')
        args = ", ".join(f["name"] for f in fields)
        lines.append(f'        Py{name} {{ {args} }}')
        lines.append(f'    }}')
        lines.append(f'    fn __repr__(&self) -> String {{')
        repr_args = ", ".join(f'self.{f["name"]}' for f in fields)
        fmt_str = ", ".join(f'{f["name"]}={{}}' for f in fields)
        lines.append(f'        format!("{name}({fmt_str})", {repr_args})')
        lines.append(f'    }}')
        lines.append(f'}}')
        # Conversion: Py wrapper → Almide type
        lines.append(f'impl From<&Py{name}> for {name} {{')
        lines.append(f'    fn from(p: &Py{name}) -> Self {{')
        args = ", ".join(f'{f["name"]}: p.{f["name"]}.clone()' for f in fields)
        lines.append(f'        {name} {{ {args} }}')
        lines.append(f'    }}')
        lines.append(f'}}')
        lines.append(f'impl From<{name}> for Py{name} {{')
        lines.append(f'    fn from(a: {name}) -> Self {{')
        args = ", ".join(f'{f["name"]}: a.{f["name"]}' for f in fields)
        lines.append(f'        Py{name} {{ {args} }}')
        lines.append(f'    }}')
        lines.append(f'}}')
        lines.append("")

    if t["kind"]["kind"] == "variant":
        cases = t["kind"]["cases"]
        lines.append(f'#[pyclass(name = "{name}")]')
        lines.append(f'#[derive(Clone)]')
        lines.append(f'struct Py{name} {{ inner: {name} }}')
        lines.append(f'#[pymethods]')
        lines.append(f'impl Py{name} {{')
        for case in cases:
            cname = case["name"].lower()
            if case.get("payload") and case["payload"]["kind"] == "tuple":
                pfields = case["payload"]["fields"]
                params = ", ".join(f'v{i}: {rust_type(pf)}' for i, pf in enumerate(pfields))
                args = ", ".join(f'v{i}' for i in range(len(pfields)))
                lines.append(f'    #[staticmethod]')
                lines.append(f'    fn {cname}({params}) -> Self {{')
                lines.append(f'        Py{name} {{ inner: {name}::{case["name"]}({args}) }}')
                lines.append(f'    }}')
            else:
                lines.append(f'    #[staticmethod]')
                lines.append(f'    fn {cname}() -> Self {{')
                lines.append(f'        Py{name} {{ inner: {name}::{case["name"]} }}')
                lines.append(f'    }}')
        lines.append(f'}}')
        lines.append(f'impl From<&Py{name}> for {name} {{')
        lines.append(f'    fn from(p: &Py{name}) -> Self {{ p.inner.clone() }}')
        lines.append(f'}}')
        lines.append("")

# Generate PyO3 wrapper functions
for fn in iface["functions"]:
    fname = fn["name"]
    # Build params
    param_strs = []
    call_args = []
    for p in fn["params"]:
        ptype = p["type"]
        if ptype["kind"] == "named":
            param_strs.append(f'{p["name"]}: Py{ptype["name"]}')
            call_args.append(f'{ptype["name"]}::from(&{p["name"]})')
        else:
            param_strs.append(f'{p["name"]}: {rust_type(ptype)}')
            call_args.append(p["name"])
    params_str = ", ".join(param_strs)
    args_str = ", ".join(call_args)

    ret = fn["return"]
    if ret["kind"] == "named":
        ret_type = f'Py{ret["name"]}'
        ret_wrap = f'Py{ret["name"]}::from({fname}({args_str}))'
    else:
        ret_type = rust_type(ret)
        ret_wrap = f'{fname}({args_str})'

    doc = fn.get("doc", "")
    lines.append(f'/// {doc}')
    lines.append(f'#[pyfunction]')
    lines.append(f'#[pyo3(name = "{fname}")]')
    lines.append(f'fn py_{fname}({params_str}) -> {ret_type} {{')
    lines.append(f'    {ret_wrap}')
    lines.append(f'}}')
    lines.append("")

# Generate module
lines.append('#[pymodule]')
lines.append('fn almide_mathlib(m: &Bound<\'_, PyModule>) -> PyResult<()> {')
for t in iface["types"]:
    lines.append(f'    m.add_class::<Py{t["name"]}>()?;')
for fn in iface["functions"]:
    lines.append(f'    m.add_function(wrap_pyfunction!(py_{fn["name"]}, m)?)?;')
lines.append('    Ok(())')
lines.append('}')

# Write output
with open("src/lib.rs", "w") as f:
    f.write("\n".join(lines))

# Generate .pyi stub
pyi = []
pyi.append(f'"""Almide module: {iface["module"]}"""')
pyi.append("")
for t in iface["types"]:
    name = t["name"]
    doc = t.get("doc", "")
    if t["kind"]["kind"] == "record":
        pyi.append(f'class {name}:')
        if doc: pyi.append(f'    """{doc}"""')
        fields = t["kind"]["fields"]
        for fld in fields:
            pyi.append(f'    {fld["name"]}: {py_type(fld["type"])}')
        params = ", ".join(f'{fld["name"]}: {py_type(fld["type"])}' for fld in fields)
        pyi.append(f'    def __init__(self, {params}) -> None: ...')
        pyi.append("")
    elif t["kind"]["kind"] == "variant":
        pyi.append(f'class {name}:')
        if doc: pyi.append(f'    """{doc}"""')
        for case in t["kind"]["cases"]:
            cname = case["name"].lower()
            if case.get("payload") and case["payload"]["kind"] == "tuple":
                params = ", ".join(f'v{i}: {py_type(pf)}' for i, pf in enumerate(case["payload"]["fields"]))
                pyi.append(f'    @staticmethod')
                pyi.append(f'    def {cname}({params}) -> {name}: ...')
            else:
                pyi.append(f'    @staticmethod')
                pyi.append(f'    def {cname}() -> {name}: ...')
        pyi.append("")

for fn in iface["functions"]:
    params = ", ".join(f'{p["name"]}: {py_type(p["type"])}' for p in fn["params"])
    ret = py_type(fn["return"])
    doc = fn.get("doc", "")
    pyi.append(f'def {fn["name"]}({params}) -> {ret}:')
    if doc: pyi.append(f'    """{doc}"""')
    pyi.append(f'    ...')
    pyi.append("")

with open("almide_mathlib.pyi", "w") as f:
    f.write("\n".join(pyi))

print("Generated: src/lib.rs + almide_mathlib.pyi")
