"""
Generate a Ruby native extension via Magnus from an Almide Module Interface.

Reads:
  - interface.json  (Module Interface from `almide --emit-interface`)
  - mathlib.rs      (generated Rust source from `almide --target rust`)

Produces:
  - src/lib.rs   (Rust source with Magnus wrappers)
  - Cargo.toml

Usage:
  python3 generate_magnus.py [--interface interface.json] [--rust mathlib.rs] [--outdir .]
"""

import json
import argparse
import os


def rust_type(tref):
    k = tref["kind"]
    if k == "float": return "f64"
    if k == "int": return "i64"
    if k == "string": return "String"
    if k == "bool": return "bool"
    if k == "named": return tref["name"]
    if k == "option": return f"Option<{rust_type(tref['inner'])}>"
    if k == "list": return f"Vec<{rust_type(tref['inner'])}>"
    return "/* unknown */"


def generate(iface, rust_source, module_name, outdir):
    mod_ruby = f"Almide{module_name.capitalize()}"
    lines = []
    lines.append("// AUTO-GENERATED by almide-lander — do not edit")
    lines.append("use magnus::{prelude::*, function, method, Ruby, Error};")
    lines.append("use std::f64::consts::PI;")
    lines.append("")

    # ── Inline math runtime ──
    lines.append("// Almide math runtime (inlined)")
    lines.append("fn almide_rt_math_sqrt(x: f64) -> f64 { x.sqrt() }")
    lines.append("fn almide_rt_math_pi() -> f64 { PI }")
    lines.append("")

    # ── Types ──
    for t in iface["types"]:
        name = t["name"]
        if t["kind"]["kind"] == "record":
            fields = t["kind"]["fields"]
            lines.append(f'#[magnus::wrap(class = "{mod_ruby}::{name}")]')
            lines.append(f'#[derive(Clone, Debug)]')
            lines.append(f'struct {name} {{')
            for f in fields:
                lines.append(f'    {f["name"]}: {rust_type(f["type"])},')
            lines.append('}')
            lines.append('')
            lines.append(f'impl {name} {{')
            # Constructor
            params = ", ".join(f'{f["name"]}: {rust_type(f["type"])}' for f in fields)
            args = ", ".join(f["name"] for f in fields)
            lines.append(f'    fn new({params}) -> Self {{ {name} {{ {args} }} }}')
            # Getters
            for f in fields:
                lines.append(f'    fn {f["name"]}(&self) -> {rust_type(f["type"])} {{ self.{f["name"]}.clone() }}')
            # Inspect
            fmt_parts = ", ".join(f'{f["name"]}={{}}' for f in fields)
            fmt_args = ", ".join(f'self.{f["name"]}' for f in fields)
            lines.append(f'    fn inspect(&self) -> String {{ format!("{name}({fmt_parts})", {fmt_args}) }}')
            lines.append('}')
            lines.append('')

        elif t["kind"]["kind"] == "variant":
            cases = t["kind"]["cases"]
            # Use a wrapper struct with tag + values for simplicity
            lines.append(f'#[magnus::wrap(class = "{mod_ruby}::{name}")]')
            lines.append(f'#[derive(Clone, Debug)]')
            lines.append(f'struct {name} {{ tag: String, values: Vec<f64> }}')
            lines.append('')
            lines.append(f'impl {name} {{')
            for case in cases:
                cname = case["name"].lower()
                if case.get("payload") and case["payload"]["kind"] == "tuple":
                    pfields = case["payload"]["fields"]
                    params = ", ".join(f'v{i}: {rust_type(pf)}' for i, pf in enumerate(pfields))
                    vals = ", ".join(f'v{i}' for i in range(len(pfields)))
                    lines.append(f'    fn {cname}({params}) -> Self {{ {name} {{ tag: "{case["name"]}".into(), values: vec![{vals}] }} }}')
                else:
                    lines.append(f'    fn {cname}() -> Self {{ {name} {{ tag: "{case["name"]}".into(), values: vec![] }} }}')
            lines.append(f'    fn inspect(&self) -> String {{ format!("{name}::{{}}({{}:?})", self.tag, self.values) }}')
            lines.append('}')
            lines.append('')

    # ── Wrapper functions ──
    for fn_def in iface["functions"]:
        fname = fn_def["name"]
        params = []
        body_args = []
        for p in fn_def["params"]:
            ptype = p["type"]
            if ptype["kind"] == "named":
                params.append(f'{p["name"]}: &{ptype["name"]}')
            else:
                params.append(f'{p["name"]}: {rust_type(ptype)}')
            body_args.append(p["name"])

        ret = fn_def["return"]
        ret_type = rust_type(ret) if ret["kind"] != "named" else fn_def["return"]["name"]

        params_str = ", ".join(params)

        # Generate function body based on the original logic
        lines.append(f'fn rb_{fname}({params_str}) -> {ret_type} {{')

        # Simple delegation — for the mathlib demo we hardcode the known functions
        # A real generator would parse the Rust source more carefully
        if fname == "distance":
            lines.append('    let dx = a.x - b.x;')
            lines.append('    let dy = a.y - b.y;')
            lines.append('    almide_rt_math_sqrt(dx * dx + dy * dy)')
        elif fname == "area":
            lines.append('    if shape.tag == "Circle" { almide_rt_math_pi() * shape.values[0] * shape.values[0] }')
            lines.append('    else { shape.values[0] * shape.values[1] }')
        elif fname == "midpoint":
            lines.append(f'    {ret_type} {{ x: (a.x + b.x) / 2.0, y: (a.y + b.y) / 2.0 }}')
        elif fname == "describe":
            lines.append('    if shape.tag == "Circle" { format!("circle with radius {}", shape.values[0]) }')
            lines.append('    else { format!("rectangle {}x{}", shape.values[0], shape.values[1]) }')
        else:
            lines.append(f'    todo!("{fname}")')
        lines.append('}')
        lines.append('')

    # ── Init ──
    lines.append('#[magnus::init]')
    lines.append('fn init(ruby: &Ruby) -> Result<(), Error> {')
    lines.append(f'    let module = ruby.define_module("{mod_ruby}")?;')
    lines.append('')

    for t in iface["types"]:
        name = t["name"]
        lines.append(f'    let {name.lower()}_cls = module.define_class("{name}", ruby.class_object())?;')
        if t["kind"]["kind"] == "record":
            fields = t["kind"]["fields"]
            lines.append(f'    {name.lower()}_cls.define_singleton_method("new", function!({name}::new, {len(fields)}))?;')
            for f in fields:
                lines.append(f'    {name.lower()}_cls.define_method("{f["name"]}", method!({name}::{f["name"]}, 0))?;')
            lines.append(f'    {name.lower()}_cls.define_method("inspect", method!({name}::inspect, 0))?;')
            lines.append(f'    {name.lower()}_cls.define_method("to_s", method!({name}::inspect, 0))?;')
        elif t["kind"]["kind"] == "variant":
            for case in t["kind"]["cases"]:
                cname = case["name"].lower()
                nargs = len(case.get("payload", {}).get("fields", []))
                lines.append(f'    {name.lower()}_cls.define_singleton_method("{cname}", function!({name}::{cname}, {nargs}))?;')
            lines.append(f'    {name.lower()}_cls.define_method("inspect", method!({name}::inspect, 0))?;')
        lines.append('')

    for fn_def in iface["functions"]:
        fname = fn_def["name"]
        nargs = len(fn_def["params"])
        lines.append(f'    module.define_module_function("{fname}", function!(rb_{fname}, {nargs}))?;')

    lines.append('')
    lines.append('    Ok(())')
    lines.append('}')

    # Write files
    src_dir = os.path.join(outdir, "src")
    os.makedirs(src_dir, exist_ok=True)

    with open(os.path.join(src_dir, "lib.rs"), 'w') as f:
        f.write('\n'.join(lines) + '\n')

    cargo = f"""[package]
name = "almide-{module_name}-ruby"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "almide_{module_name}"

[dependencies]
magnus = "0.7"
"""
    with open(os.path.join(outdir, "Cargo.toml"), 'w') as f:
        f.write(cargo)

    print(f"Generated: src/lib.rs + Cargo.toml (Ruby/Magnus)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Ruby Magnus binding from Almide Module Interface")
    parser.add_argument("--interface", default="interface.json")
    parser.add_argument("--rust", default="mathlib.rs")
    parser.add_argument("--outdir", default=".")
    args = parser.parse_args()

    with open(args.interface) as f:
        iface = json.load(f)

    rust_source = ""
    if os.path.exists(args.rust):
        with open(args.rust) as f:
            rust_source = f.read()

    module_name = iface["module"]
    generate(iface, rust_source, module_name, args.outdir)
