"""
Generate a TypeScript/JS wrapper module for an Almide WASM binary.

Reads:
  - interface.json  (Module Interface from `almide --emit-interface`)
  - mathlib.wasm    (WASM binary from `almide build --target wasm`)

Produces:
  - almide_<module>.ts   (TypeScript wrapper with typed exports)
  - almide_<module>.d.ts (Type declarations for JS consumers)

Usage:
  python3 generate_wasm_js.py [--interface interface.json] [--outdir .]
"""

import json
import argparse
import os

def ts_type(tref):
    k = tref["kind"]
    if k in ("int", "float"): return "number"
    if k == "string": return "string"
    if k == "bool": return "boolean"
    if k == "unit": return "void"
    if k == "named": return tref["name"]
    if k == "option": return f"({ts_type(tref['inner'])} | null)"
    if k == "list": return f"{ts_type(tref['inner'])}[]"
    if k == "tuple": return f"[{', '.join(ts_type(e) for e in tref['elements'])}]"
    if k == "result": return ts_type(tref["ok"])
    if k == "map": return f"Map<{ts_type(tref['key'])}, {ts_type(tref['value'])}>"
    if k == "fn":
        params = ", ".join(f"arg{i}: {ts_type(p)}" for i, p in enumerate(tref["params"]))
        return f"({params}) => {ts_type(tref['return'])}"
    return "any"


def generate(iface, module_name, outdir):
    lines = []
    dts_lines = []

    lines.append('/**')
    lines.append(f' * TypeScript wrapper for the Almide {module_name} WASM module.')
    lines.append(' * AUTO-GENERATED by almide-lander — do not edit.')
    lines.append(' */')
    lines.append('')

    # ── Public types ──
    lines.append('// ---------- Public types ----------')
    dts_lines.append(f'// Type declarations for almide_{module_name}')
    dts_lines.append('')

    for t in iface["types"]:
        name = t["name"]
        doc = t.get("doc", "")
        if t["kind"]["kind"] == "record":
            fields = t["kind"]["fields"]
            if doc:
                lines.append(f'/** {doc} */')
                dts_lines.append(f'/** {doc} */')
            lines.append(f'export interface {name} {{')
            dts_lines.append(f'export interface {name} {{')
            for f in fields:
                ftype = ts_type(f["type"])
                lines.append(f'  {f["name"]}: {ftype};')
                dts_lines.append(f'  {f["name"]}: {ftype};')
            lines.append('}')
            dts_lines.append('}')
            lines.append('')
            dts_lines.append('')

        elif t["kind"]["kind"] == "variant":
            cases = t["kind"]["cases"]
            if doc:
                lines.append(f'/** {doc} */')
                dts_lines.append(f'/** {doc} */')
            parts = []
            for case in cases:
                if case.get("payload") and case["payload"]["kind"] == "tuple":
                    pfields = case["payload"]["fields"]
                    fnames = [f'v{i}' for i in range(len(pfields))]
                    obj_fields = "; ".join(f'{fn}: {ts_type(pf)}' for fn, pf in zip(fnames, pfields))
                    parts.append(f'{{ tag: "{case["name"]}"; {obj_fields} }}')
                else:
                    parts.append(f'{{ tag: "{case["name"]}" }}')
            union = "\n  | ".join(parts)
            lines.append(f'export type {name} =\n  | {union};')
            dts_lines.append(f'export type {name} =\n  | {union};')
            lines.append('')
            dts_lines.append('')

    # ── Shape constructor helpers ──
    for t in iface["types"]:
        if t["kind"]["kind"] == "variant":
            name = t["name"]
            lines.append(f'export const {name} = {{')
            for case in t["kind"]["cases"]:
                cname = case["name"][0].lower() + case["name"][1:]
                if case.get("payload") and case["payload"]["kind"] == "tuple":
                    pfields = case["payload"]["fields"]
                    params = ", ".join(f'v{i}: {ts_type(pf)}' for i, pf in enumerate(pfields))
                    args = ", ".join(f'v{i}' for i in range(len(pfields)))
                    lines.append(f'  {cname}({params}): {name} {{ return {{ tag: "{case["name"]}", {args} }}; }},')
                else:
                    lines.append(f'  {cname}(): {name} {{ return {{ tag: "{case["name"]}" }}; }},')
            lines.append('};')
            lines.append('')

    # ── Internals ──
    lines.append('// ---------- Internals ----------')
    lines.append('')
    lines.append('let memory: WebAssembly.Memory;')
    lines.append('let view: DataView;')
    lines.append('let alloc: (n: number) => number;')

    # Declare wasm function bindings
    for fn in iface["functions"]:
        fname = fn["name"]
        lines.append(f'let wasm_{fname}: Function;')
    lines.append('')
    lines.append('function refreshView(): void { view = new DataView(memory.buffer); }')
    lines.append('')

    # ── Memory layout helpers ──
    lines.append('// ---------- Memory layout helpers ----------')
    lines.append('')
    for t in iface["types"]:
        name = t["name"]
        if t["kind"]["kind"] == "record":
            fields = t["kind"]["fields"]
            # Calculate size: each field is 8 bytes (f64) or 8 bytes (i64) or variable
            offset = 0
            write_lines = []
            read_lines = []
            for f in fields:
                ftype = f["type"]["kind"]
                if ftype in ("float",):
                    write_lines.append(f'  view.setFloat64(ptr + {offset}, p.{f["name"]}, true);')
                    read_lines.append(f'    {f["name"]}: view.getFloat64(ptr + {offset}, true),')
                    offset += 8
                elif ftype in ("int",):
                    write_lines.append(f'  view.setBigInt64(ptr + {offset}, BigInt(p.{f["name"]}), true);')
                    read_lines.append(f'    {f["name"]}: Number(view.getBigInt64(ptr + {offset}, true)),')
                    offset += 8
                elif ftype in ("bool",):
                    write_lines.append(f'  view.setUint8(ptr + {offset}, p.{f["name"]} ? 1 : 0);')
                    read_lines.append(f'    {f["name"]}: view.getUint8(ptr + {offset}) !== 0,')
                    offset += 1
                else:
                    write_lines.append(f'  // TODO: marshal {f["name"]}: {ftype}')
                    read_lines.append(f'    // TODO: read {f["name"]}: {ftype}')
                    offset += 8  # guess

            lines.append(f'function write{name}(p: {name}): number {{')
            lines.append(f'  const ptr = alloc({offset});')
            lines.append(f'  refreshView();')
            lines.extend(write_lines)
            lines.append(f'  return ptr;')
            lines.append(f'}}')
            lines.append('')
            lines.append(f'function read{name}(ptr: number): {name} {{')
            lines.append(f'  refreshView();')
            lines.append(f'  return {{')
            lines.extend(read_lines)
            lines.append(f'  }};')
            lines.append(f'}}')
            lines.append('')

        elif t["kind"]["kind"] == "variant":
            cases = t["kind"]["cases"]
            lines.append(f'function write{name}(s: {name}): number {{')
            for ci, case in enumerate(cases):
                cond = "if" if ci == 0 else "} else if"
                lines.append(f'  {cond} (s.tag === "{case["name"]}") {{')
                if case.get("payload") and case["payload"]["kind"] == "tuple":
                    pfields = case["payload"]["fields"]
                    size = 4 + sum(8 for _ in pfields)
                    lines.append(f'    const ptr = alloc({size});')
                    lines.append(f'    refreshView();')
                    lines.append(f'    view.setInt32(ptr, {ci}, true);')
                    offset = 4
                    for fi, pf in enumerate(pfields):
                        cast = "s" if len(pfields) == 1 else "s"
                        lines.append(f'    view.setFloat64(ptr + {offset}, (s as any).v{fi}, true);')
                        offset += 8
                    lines.append(f'    return ptr;')
                else:
                    lines.append(f'    const ptr = alloc(4);')
                    lines.append(f'    refreshView();')
                    lines.append(f'    view.setInt32(ptr, {ci}, true);')
                    lines.append(f'    return ptr;')
            lines.append('  }')
            lines.append(f'  throw new Error("Unknown {name} tag");')
            lines.append('}')
            lines.append('')

    # String reader
    lines.append('function readString(ptr: number): string {')
    lines.append('  refreshView();')
    lines.append('  const len = view.getInt32(ptr, true);')
    lines.append('  const bytes = new Uint8Array(memory.buffer, ptr + 4, len);')
    lines.append('  return new TextDecoder().decode(bytes);')
    lines.append('}')
    lines.append('')

    # ── Public API functions ──
    lines.append('// ---------- Public API ----------')
    lines.append('')
    for fn in iface["functions"]:
        fname = fn["name"]
        doc = fn.get("doc", "")
        ret_kind = fn["return"]["kind"]

        # Build call args
        params_ts = []
        call_args = []
        for p in fn["params"]:
            ptype = p["type"]
            params_ts.append(f'{p["name"]}: {ts_type(ptype)}')
            if ptype["kind"] == "named":
                call_args.append(f'write{ptype["name"]}({p["name"]})')
            else:
                call_args.append(p["name"])

        params_str = ", ".join(params_ts)
        args_str = ", ".join(call_args)
        ret_ts = ts_type(fn["return"])

        if doc:
            lines.append(f'/** {doc} */')
            dts_lines.append(f'/** {doc} */')
        dts_lines.append(f'export function {fname}({params_str}): {ret_ts};')

        lines.append(f'export function {fname}({params_str}): {ret_ts} {{')
        if ret_kind == "named":
            ret_name = fn["return"]["name"]
            lines.append(f'  return read{ret_name}(wasm_{fname}({args_str}));')
        elif ret_kind == "string":
            lines.append(f'  return readString(wasm_{fname}({args_str}));')
        else:
            lines.append(f'  return wasm_{fname}({args_str});')
        lines.append('}')
        lines.append('')

    # ── Init ──
    lines.append('// ---------- Initialisation ----------')
    lines.append('')
    lines.append('export async function init(wasmPath: string): Promise<void> {')
    lines.append('  const bytes = await Deno.readFile(wasmPath);')
    lines.append('  const mod = new WebAssembly.Module(bytes);')
    lines.append('  const importObject: Record<string, Record<string, WebAssembly.ImportValue>> = {};')
    lines.append('  for (const imp of WebAssembly.Module.imports(mod)) {')
    lines.append('    if (!importObject[imp.module]) importObject[imp.module] = {};')
    lines.append('    if (imp.kind === "function") {')
    lines.append('      importObject[imp.module][imp.name] = (..._args: unknown[]) => 0;')
    lines.append('    }')
    lines.append('  }')
    lines.append('  const instance = new WebAssembly.Instance(mod, importObject);')
    lines.append('  const ex = instance.exports;')
    lines.append('  memory = ex.memory as WebAssembly.Memory;')
    lines.append('  alloc = ex.__alloc as (n: number) => number;')
    for fn in iface["functions"]:
        fname = fn["name"]
        lines.append(f'  wasm_{fname} = ex.{fname} as Function;')
    lines.append('  refreshView();')
    lines.append('}')

    # Write files
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, f'almide_{module_name}.ts'), 'w') as f:
        f.write('\n'.join(lines) + '\n')
    with open(os.path.join(outdir, f'almide_{module_name}.d.ts'), 'w') as f:
        f.write('\n'.join(dts_lines) + '\n')

    print(f"Generated: almide_{module_name}.ts + almide_{module_name}.d.ts")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate WASM-JS wrapper from Almide Module Interface")
    parser.add_argument("--interface", default="interface.json")
    parser.add_argument("--outdir", default=".")
    args = parser.parse_args()

    with open(args.interface) as f:
        iface = json.load(f)

    module_name = iface["module"]
    generate(iface, module_name, args.outdir)
