#![allow(unused_parens, unused_variables, dead_code, unused_imports, unused_mut)]
// AUTO-GENERATED by almide-bridge — do not edit


use std::collections::HashMap;
use std::collections::HashSet;
trait AlmideConcat<Rhs> { type Output; fn concat(self, rhs: Rhs) -> Self::Output; }
impl AlmideConcat<String> for String { type Output = String; #[inline(always)] fn concat(self, rhs: String) -> String { format!("{}{}", self, rhs) } }
impl AlmideConcat<&str> for String { type Output = String; #[inline(always)] fn concat(self, rhs: &str) -> String { format!("{}{}", self, rhs) } }
impl AlmideConcat<String> for &str { type Output = String; #[inline(always)] fn concat(self, rhs: String) -> String { format!("{}{}", self, rhs) } }
impl AlmideConcat<&str> for &str { type Output = String; #[inline(always)] fn concat(self, rhs: &str) -> String { format!("{}{}", self, rhs) } }
impl<T: Clone> AlmideConcat<Vec<T>> for Vec<T> { type Output = Vec<T>; #[inline(always)] fn concat(self, rhs: Vec<T>) -> Vec<T> { let mut r = self; r.extend(rhs); r } }
macro_rules! almide_eq { ($a:expr, $b:expr) => { ($a) == ($b) }; }
macro_rules! almide_ne { ($a:expr, $b:expr) => { ($a) != ($b) }; }
// math extern — Rust native implementations

// Trigonometry
#[inline(always)] pub fn almide_rt_math_sin(x: f64) -> f64 { x.sin() }
#[inline(always)] pub fn almide_rt_math_cos(x: f64) -> f64 { x.cos() }
#[inline(always)] pub fn almide_rt_math_tan(x: f64) -> f64 { x.tan() }
#[inline(always)] pub fn almide_rt_math_asin(x: f64) -> f64 { x.asin() }
#[inline(always)] pub fn almide_rt_math_acos(x: f64) -> f64 { x.acos() }
#[inline(always)] pub fn almide_rt_math_atan(x: f64) -> f64 { x.atan() }
#[inline(always)] pub fn almide_rt_math_atan2(y: f64, x: f64) -> f64 { y.atan2(x) }

// Logarithms / exponentials
#[inline(always)] pub fn almide_rt_math_log(x: f64) -> f64 { x.ln() }
#[inline(always)] pub fn almide_rt_math_log2(x: f64) -> f64 { x.log2() }
#[inline(always)] pub fn almide_rt_math_log10(x: f64) -> f64 { x.log10() }
#[inline(always)] pub fn almide_rt_math_exp(x: f64) -> f64 { x.exp() }
#[inline(always)] pub fn almide_rt_math_pow(base: i64, exp: i64) -> i64 { base.pow(exp as u32) }

// Rounding
#[inline(always)] pub fn almide_rt_math_abs(x: i64) -> i64 { x.abs() }
#[inline(always)] pub fn almide_rt_math_ceil(x: f64) -> f64 { x.ceil() }
#[inline(always)] pub fn almide_rt_math_floor(x: f64) -> f64 { x.floor() }
#[inline(always)] pub fn almide_rt_math_round(x: f64) -> f64 { x.round() }
#[inline(always)] pub fn almide_rt_math_sqrt(x: f64) -> f64 { x.sqrt() }

// Constants
#[inline(always)] pub fn almide_rt_math_pi() -> f64 { std::f64::consts::PI }
#[inline(always)] pub fn almide_rt_math_e() -> f64 { std::f64::consts::E }
#[inline(always)] pub fn almide_rt_math_inf() -> f64 { f64::INFINITY }
#[inline(always)] pub fn almide_rt_math_is_nan(x: f64) -> bool { x.is_nan() }

// Int min/max/sign
#[inline(always)] pub fn almide_rt_math_min(a: i64, b: i64) -> i64 { a.min(b) }
#[inline(always)] pub fn almide_rt_math_max(a: i64, b: i64) -> i64 { a.max(b) }
#[inline(always)] pub fn almide_rt_math_sign(n: i64) -> i64 { if n > 0 { 1 } else if n < 0 { -1 } else { 0 } }

// Float min/max
#[inline(always)] pub fn almide_rt_math_fmin(a: f64, b: f64) -> f64 { a.min(b) }
#[inline(always)] pub fn almide_rt_math_fmax(a: f64, b: f64) -> f64 { a.max(b) }
#[inline(always)] pub fn almide_rt_math_fpow(base: f64, exp: f64) -> f64 { base.powf(exp) }

// Factorial / combinatorics
pub fn almide_rt_math_factorial(n: i64) -> i64 {
    (1..=n).product()
}
pub fn almide_rt_math_choose(n: i64, k: i64) -> i64 {
    if k < 0 || k > n { return 0; }
    let k = k.min(n - k) as u64;
    let mut result: u64 = 1;
    for i in 0..k {
        result = result * (n as u64 - i) / (i + 1);
    }
    result as i64
}
pub fn almide_rt_math_log_gamma(x: f64) -> f64 {
    // Stirling approximation
    let t = x + 6.5;
    (2.5066282746310005_f64).ln()
        + (x - 0.5) * t.ln()
        - t
        + (1.000000000190015
            + 76.18009172947146 / x
            + -86.50532032941677 / (x + 1.0)
            + 24.01409824083091 / (x + 2.0)
            + -1.231739572450155 / (x + 3.0)
            + 0.001208650973866179 / (x + 4.0)
            + -0.000005395239384953 / (x + 5.0))
            .ln()
}


#[repr(C)]
#[derive(Clone, Debug, PartialEq, PartialOrd)]
pub struct Point {
    pub x: f64,
    pub y: f64,
}

#[repr(C)]
#[derive(Clone, Debug, PartialEq, PartialOrd)]
pub enum Shape {
    Circle(f64),
    Rect(f64, f64)
}

pub fn distance(a: Point, b: Point) -> f64 { let dx: f64 = (a.clone().x - b.clone().x);
let dy: f64 = (a.clone().y - b.clone().y);
almide_rt_math_sqrt(((dx * dx) + (dy * dy))) }

pub fn area(shape: Shape) -> f64 { match shape.clone() { Shape::Circle(r) => ((almide_rt_math_pi() * r) * r),
Shape::Rect(w, h) => (w * h), } }

pub fn midpoint(a: Point, b: Point) -> Point { Point { x: ((a.clone().x + b.clone().x) / 2f64), y: ((a.clone().y + b.clone().y) / 2f64) } }

pub fn describe(shape: Shape) -> String { match shape.clone() { Shape::Circle(r) => format!("circle with radius {}", r),
Shape::Rect(w, h) => format!("rectangle {}x{}", w, h), } }

// Bridge helpers: alloc/free for foreign callers
#[no_mangle]
pub extern "C" fn bridge_alloc(len: i32) -> *mut u8 {
    let mut buf = Vec::<u8>::with_capacity(len as usize);
    let ptr = buf.as_mut_ptr();
    std::mem::forget(buf);
    ptr
}

#[no_mangle]
pub extern "C" fn bridge_free(ptr: *mut u8, len: i32) {
    if ptr.is_null() { return; }
    unsafe { drop(Vec::from_raw_parts(ptr, 0, len as usize)); }
}

#[no_mangle]
pub extern "C" fn bridge_distance(args: *const u8, args_len: i32, out_ptr: *mut u8, out_cap: i32) -> i32 {
    let buf = unsafe { std::slice::from_raw_parts(args, args_len as usize) };
    let mut pos: usize = 0;
    let mut out: Vec<u8> = Vec::new();
    let a = { let v = Point { x: { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }, y: { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v } }; v };
    let b = { let v = Point { x: { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }, y: { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v } }; v };
    let __result = distance(a, b);
    out.extend_from_slice(&(__result).to_be_bytes());
    let out_len = out.len().min(out_cap as usize);
    unsafe { std::ptr::copy_nonoverlapping(out.as_ptr(), out_ptr, out_len); }
    out.len() as i32
}

#[no_mangle]
pub extern "C" fn bridge_area(args: *const u8, args_len: i32, out_ptr: *mut u8, out_cap: i32) -> i32 {
    let buf = unsafe { std::slice::from_raw_parts(args, args_len as usize) };
    let mut pos: usize = 0;
    let mut out: Vec<u8> = Vec::new();
    let shape = { let tag = u32::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3]]); pos += 4; match tag { 0 => Shape::Circle({ let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }), 1 => Shape::Rect({ let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }, { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }), _ => unreachable!() } };
    let __result = area(shape);
    out.extend_from_slice(&(__result).to_be_bytes());
    let out_len = out.len().min(out_cap as usize);
    unsafe { std::ptr::copy_nonoverlapping(out.as_ptr(), out_ptr, out_len); }
    out.len() as i32
}

#[no_mangle]
pub extern "C" fn bridge_midpoint(args: *const u8, args_len: i32, out_ptr: *mut u8, out_cap: i32) -> i32 {
    let buf = unsafe { std::slice::from_raw_parts(args, args_len as usize) };
    let mut pos: usize = 0;
    let mut out: Vec<u8> = Vec::new();
    let a = { let v = Point { x: { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }, y: { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v } }; v };
    let b = { let v = Point { x: { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }, y: { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v } }; v };
    let __result = midpoint(a, b);
    { let __r = __result;
    out.extend_from_slice(&(__r.x).to_be_bytes());
    out.extend_from_slice(&(__r.y).to_be_bytes());
    }
    let out_len = out.len().min(out_cap as usize);
    unsafe { std::ptr::copy_nonoverlapping(out.as_ptr(), out_ptr, out_len); }
    out.len() as i32
}

#[no_mangle]
pub extern "C" fn bridge_describe(args: *const u8, args_len: i32, out_ptr: *mut u8, out_cap: i32) -> i32 {
    let buf = unsafe { std::slice::from_raw_parts(args, args_len as usize) };
    let mut pos: usize = 0;
    let mut out: Vec<u8> = Vec::new();
    let shape = { let tag = u32::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3]]); pos += 4; match tag { 0 => Shape::Circle({ let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }), 1 => Shape::Rect({ let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }, { let v = f64::from_be_bytes([buf[pos],buf[pos+1],buf[pos+2],buf[pos+3],buf[pos+4],buf[pos+5],buf[pos+6],buf[pos+7]]); pos += 8; v }), _ => unreachable!() } };
    let __result = describe(shape);
    { let s = __result; let sb = s.as_bytes();
      out.extend_from_slice(&(sb.len() as u32).to_be_bytes());
      out.extend_from_slice(sb); }
    let out_len = out.len().min(out_cap as usize);
    unsafe { std::ptr::copy_nonoverlapping(out.as_ptr(), out_ptr, out_len); }
    out.len() as i32
}
